name: Daily Build

on:
  schedule:            # каждый день 03:00 MSK (= 00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:   # ручной запуск из вкладки “Actions”

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
      KEY_SOURCE:          ${{ secrets.KEY_SOURCE }}
      AWS_ACCESS_KEY_ID:   ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      BUCKET:              ${{ secrets.BUCKET_NAME }}
      REGION:              ${{ secrets.BUCKET_REGION }}

    steps:
      # 1 — получаем код репозитория
      - uses: actions/checkout@v4

      # 2 — ставим Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3 — устанавливаем зависимости (одной командой)
      - run: |
          pip install "openai==0.28.*" feedgen boto3 markdown

      # 4 — генерируем markdown-статьи
      - run: python scripts/generate.py

      # 5 — строим сайт (html + RSS)
      - run: python scripts/build_site.py

      # 6 — заливаем в Object Storage
      - run: python scripts/deploy.py
