name: Daily Build
on:
  schedule:          # каждый день 03:00 MSK (= 00:00 UTC)
    - cron:  '0 0 * * *'
  workflow_dispatch: # ручной запуск
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      KEY_SOURCE:     ${{ secrets.KEY_SOURCE }}
      AWS_ACCESS_KEY_ID:     ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      BUCKET:  ${{ secrets.BUCKET_NAME }}
      REGION:  ${{ secrets.BUCKET_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install "openai==0.28.*" requests feedgen boto3 markdown
      - run: python scripts/generate.py
      - run: python scripts/deploy.py
